export const GET_CONVERSATION_DETAILS_REQUEST = 'GET_CONVERSATION_DETAILS_REQUEST'
export const GET_CONVERSATION_DETAILS_SUCCESS = 'GET_CONVERSATION_DETAILS_SUCCESS'
export const GET_CONVERSATION_DETAILS_FAIL = 'GET_CONVERSATION_DETAILS_FAIL'


export const GET_MESSAGE_DETAILS_REQUEST = 'GET_MESSAGE_DETAILS_REQUEST'
export const GET_MESSAGE_DETAILS_SUCCESS = 'GET_MESSAGE_DETAILS_SUCCESS'
export const GET_MESSAGE_DETAILS_FAIL = 'GET_MESSAGE_DETAILS_FAIL'
