export const SUBSCRIBING_POST_DETAILS_REQUEST = 'SUBSCRIBING_POST_DETAILS_REQUEST'
export const SUBSCRIBING_POST_DETAILS_SUCCESS = 'SUBSCRIBING_POST_DETAILS_SUCCESS'
export const SUBSCRIBING_POST_DETAILS_FAIL = 'SUBSCRIBING_POST_DETAILS_FAIL'

export const NOTIFICATION_DETAILS_REQUEST = 'NOTIFICATION_DETAILS_REQUEST'
export const NOTIFICATION_DETAILS_SUCCESS = 'NOTIFICATION_DETAILS_SUCCESS'
export const NOTIFICATION_DETAILS_FAIL = 'NOTIFICATION_DETAILS_FAIL'

export const SINGLE_POST_DETAILS_REQUEST = 'SINGLE_POST_DETAILS_REQUEST'
export const SINGLE_POST_DETAILS_SUCCESS = 'SINGLE_POST_DETAILS_SUCCESS'
export const SINGLE_POST_DETAILS_FAIL = 'SINGLE_POST_DETAILS_FAIL'

export const GET_ALL_PHOTOS_DETAILS_FAIL = 'GET_ALL_PHOTOS_DETAILS_FAIL'
export const GET_ALL_PHOTOS_DETAILS_REQUEST = 'GET_ALL_PHOTOS_DETAILS_REQUEST'
export const GET_ALL_PHOTOS_DETAILS_SUCCESS = 'GET_ALL_PHOTOS_DETAILS_SUCCESS'


export const GET_ALL_VIDEOS_DETAILS_FAIL = 'GET_ALL_VIDEOS_DETAILS_FAIL'
export const GET_ALL_VIDEOS_DETAILS_REQUEST = 'GET_ALL_VIDEOS_DETAILS_REQUEST'
export const GET_ALL_VIDEOS_DETAILS_SUCCESS = 'GET_ALL_VIDEOS_DETAILS_SUCCESS'

