export const GET_RESTAURANTS_DATA_REQUEST = 'GET_RESTAURANTS_DATA_REQUEST'
export const GET_RESTAURANTS_DATA_SUCCESS = 'GET_RESTAURANTS_DATA_SUCCESS'
export const GET_RESTAURANTS_DATA_FAIL = 'GET_RESTAURANTS_DATA_FAIL'